buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:3.9.8"
        classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.0.0.2929"
    }
}

plugins {
    id 'java'
}

apply plugin: 'net.serenity-bdd.serenity-gradle-plugin'

group = 'co.com.pruebaTCS'
version = '1.0'

repositories {
    mavenCentral()
}

ext {
    serenityVersion = '3.6.12'
    junitVersion = '4.13.2'
}

dependencies {
    implementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"
    testImplementation "junit:junit:4.13.2"
    implementation 'org.seleniumhq.selenium:selenium-java:4.21.0'
    implementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
    implementation 'net.datafaker:datafaker:1.9.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    implementation "net.serenity-bdd:serenity-screenplay-rest:$serenityVersion"
    implementation "net.serenity-bdd:serenity-junit:$serenityVersion"
    implementation "io.cucumber:cucumber-java:7.14.0"
    implementation "io.cucumber:cucumber-junit:7.14.0"

}


test {
    useJUnit()
    testLogging.showStandardStreams = true
}